apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: #this is deployment labels
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels: #this labels will match with the pod
      app: nginx
  template: #this is the pod def
    metadata:
      labels:
        app: nginx
        project: roboshop
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80