apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
data: 
  username: bmlzaGFsCg
  password: bmlzaGFsMTIK
---
apiVersion: v1
kind: pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret-pod
    image: nginx
    envFrom:
    - secretRef: 
        name: secret-basic-auth
